name: Build and Release Borderless Gaming

on:
  push:
    tags:
      - 'v*.*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      APP_VERSION: ""
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3

      - name: Set version
        shell: powershell
        run: |
          $version = $Env:GITHUB_REF_NAME
          $version = $version.Replace("v", "")
          $version = $version.Replace("refs/tags/", "")
          Write-Host "Version: $version"
          $xmlPath = "version.xml"
          $appPath = "BorderlessGaming\BorderlessGaming.csproj"
          $assemblyInfoPath = "BorderlessGaming\Properties\AssemblyInfo.cs"
          
          (Get-Content -LiteralPath $xmlPath) -replace "<version>.*?</version>", "<version>$version</version>" | Set-Content -LiteralPath $xmlPath
          
          (Get-Content -LiteralPath $appPath) -replace "<ApplicationVersion>.*?</ApplicationVersion>", "<ApplicationVersion>$version</ApplicationVersion>" | Set-Content -LiteralPath $appPath
          # Replace AssemblyVersion and AssemblyFileVersion in AssemblyInfo.cs with the new version
          (Get-Content -LiteralPath $assemblyInfoPath) -replace 'AssemblyVersion\("\d+\.\d+\.\d+\.\d+"\)', "AssemblyVersion(`"$version`")" | Set-Content -LiteralPath $assemblyInfoPath
          (Get-Content -LiteralPath $assemblyInfoPath) -replace 'AssemblyFileVersion\("\d+\.\d+\.\d+\.\d+"\)', "AssemblyFileVersion(`"$version`")" | Set-Content -LiteralPath $assemblyInfoPath
          echo "APP_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

      - name: Restore NuGet packages
        run: msbuild BorderlessGaming.sln /t:Restore

      - name: Build Release
        run: msbuild BorderlessGaming.sln `
              /p:Configuration=Release `
              /p:Platform="Any CPU" `
              /p:PostBuildEvent="" `
              /p:RunPostBuildEvent=Never
      - name: Create setup (Inno Setup)
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: Installers\BorderlessGaming_Standalone_Admin.iss
          options: /O"setup" /F"BorderlessGaming_${{ env.APP_VERSION }}-setup.exe"
 
      - name: Prepare release folder
        run: |
            $version = $Env:APP_VERSION
            mkdir release
            xcopy BorderlessGaming\bin\Release\* release\ /E /H /C /I
            powershell Compress-Archive -Path "Languages\*.lang" -DestinationPath "release\Languages.zip" -Force
            powershell Compress-Archive -Path release\* -DestinationPath BorderlessGaming-$version.zip -Force
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Borderless Gaming ${{ env.APP_VERSION }}
          draft: true
          files: |
            BorderlessGaming-${{ env.APP_VERSION }}.zip
            setup\BorderlessGaming_${{ env.APP_VERSION }}-setup.exe
            version.xml
            release\Languages.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
